### ISSUE TITLE
Markers not opening

### ISSUE THREAD

**Issue by ghtesting2020** [AsherGlick/Burrito#142]
Hi i am a bit confused how to work with markers. Is it like taco where i can turn off ones i do not need so screen is not cluttered? For example if i am in crystal oasis and i do not want to see casino blitz is there no toggle to turn off only that?

also will there be a converted file for the newer maps in the latest expansion?

thank you

**Comment by AsherGlick** [comment]
We are planning on releasing a new set of features for loading taco XML markers directly https://github.com/AsherGlick/Burrito/issues/64  This will make everything a lot clearer.

But right now you cannot load `.taco` or `.zip` files, you must load `.json` files directly. You will need to unzip the converted file and load the json file within.

If you really really want to convert a different marker file *right now* you can use the https://github.com/AsherGlick/Burrito/blob/master/scripts/taco_to_burrito.py but it requires correctly formatted xml files (many taco markers are not) so you may need to adjust the xml files to fix errors to get it to work.
