### ISSUE TITLE
Unable to use any keyboard inputs in-game while Burrito is open

### ISSUE THREAD

**Issue by slothplaysnecro** [AsherGlick/Burrito#143]
~~Distro: Nobara (Fedora) 37

![image](https://github.com/AsherGlick/Burrito/assets/5749486/5ab1c0ed-66e1-4835-a3d5-defc5b0cf714)

If I click to the left of the red line, everything works fine. Mouse inputs to the right of the line go through, but keyboard inputs do not.

Burrito Link is running through the terminal.~~ Sorry, please ignore this. I'm using Wayland and need to switch to X11. Should've checked issues first.

**Comment by slothplaysnecro** [comment]
Sorry, please ignore this. I'm using Wayland and need to switch to X11. Should've checked issues first.

**Comment by AsherGlick** [comment]
Closing this based on your second comment. Hopefully in the future we will do a better job of both
1) Tracking these known workarounds in an easy to find location
and 2) Working on Wayland
Unfortunately, until I get a machine that uses wayland to play gw2, all of the wayland support in Burrito will come from community patches.
