### ISSUE TITLE
Discord ?

### ISSUE THREAD

**Issue by coderedart** [AsherGlick/Burrito#22]
using github is beyond most casual players. maybe have a burrito discord server or request a channel in the gw2 dev community server to help users/gather info for bugs in an accessible way. most people are likely to have discord because of existing communities like fast farming, hardstuck, most guilds (even smaller ones) have their own, wvw servers each have their own, most streamers have their own and such. 

having a own discord server comes with the burden of moderating and other stuff. but gives the freedom of managing and making relevant channels easier. 
while having a channel on gw2 dev community makes it much easier as there's no maintenance. 

also wanted to mention that http://gw2.link/hub exists which has a central repository of pretty much all gw2 related discord servers.

**Comment by darthmaim** [comment]
Link to the GW2 Development Community Discord is https://discord.gg/zqeHCEg in case you are not aware of that already :)

**Comment by AsherGlick** [comment]
Having a discord presence sounds like a good idea. Though I do not have the time or experience to do it myself. If someone wants to run through the steps of creating a channel or server and commit to moderating it I would be happy to sanction it as "official".

**Comment by dlamkins** [comment]
I'd recommend probably just joining the GW2 Dev Community Discord that was mentioned.  Lots of membership overlap between servers anyways, and we've got mods there so you can keep a channel there for Burrito specific conversations.  Just gotta ping any of the 3 moderators there to get a channel made.

There's also a lot of overlap between this project and others already going on that you may be interested in discussing to help remove duplicate efforts, etc.

(full disclaimer, both myself and darthmaim are 2 of the moderators there :grin:)

**Comment by AsherGlick** [comment]
I'm sold on joining the GW2 Development Community discord. Ill send you a message there.

**Comment by coderedart** [comment]
Gw2 Development Community discord now has a burrito channel.
