### ISSUE TITLE
No paths nor converted markers appear

### ISSUE THREAD

**Issue by Nuxmin** [AsherGlick/Burrito#24]
Hey there!

Trying the new and promising Burrito!

I don't know if I'm doing something wrong here's what I did:

1. Follow the steps stated on the website
2. Run the script created for the Burrito link with the path: "
3. Run the awesome Burrito!
4. Load one of the .json files inside the converted markers (also tried the zip, and the .taco file from Tekkit)
5. Here's the max I could do, nothing appears and there goes what the terminal 

![Screenshot from 2021-08-14 23-55-26](https://user-images.githubusercontent.com/55192382/129461158-bbf97ef6-299a-440d-b93e-1d5dca3cbfe6.png)

Maybe I'm doing something wrong. I hope I can help in some way to provide more feedback in order to make it better!

Thank you for your efforts!

(I also include de burrito script)

https://gist.github.com/Nuxmin/b8e060acfdaa6c3cc31f759f7cee9c99

**Comment by AsherGlick** [comment]
tw_mc_coretyria.json should definitely be loading in that map. Can you share the output of the burrito_link.exe script when you execute it?

**Comment by Nuxmin** [comment]
Of course, here it goes!

https://gist.github.com/Nuxmin/5655903e170258099fbd7590f6e82e69

**Comment by AsherGlick** [comment]
Ah! Yes, this is because of #20.
If you dont want to wait until it is fixed you can use [arcdps](https://www.deltaconnected.com/arcdps/) or any other addon that will create the memory map.

**Comment by AsherGlick** [comment]
Something I should have mentioned too is that if arcdps is crashing your system while running you can
1) Start gw2 with arcdps
2) Start burrito_link
3) Cloese gw2 (but leave burrito_link running)
4) Remove arcdps
5) Start gw2

and the link should be working.

It is cumbersome but it should work until burrito can handle the problem on its own.

**Comment by coderedart** [comment]
i had the same issue as i don't use arcdps. although i made a similar thing called jokolink, so i just used it to create the shared memory. the https://github.com/AsherGlick/Burrito/pull/26 should fix this, so no need for arc anymore.
