### ISSUE TITLE
Supporting Screen Sizes larger then 1080p

### ISSUE THREAD

**Issue by AsherGlick** [AsherGlick/Burrito#29]
Burrito was deigned around 1080p screens and had that value hard coded into it. There is no technical reason why it should not be able to be scaled up to larger screen resolutions as discussed in part of #23.

There may need to be some work on adjusting the minimap shader location code if it is not something that is already computed correctly.

This can be implemented via a setting that can be changed manually. Or more complexly it can be obtained via the size of the guild wars 2 window.

**Comment by Melechtna** [comment]
using wmctrl you can force it to be fullscreen and satisfy any resolution

**Comment by bisby** [comment]
@Melechtna in i3wm, if a window is fullscreen, the stuff in the background stops rendering. so "use fullscreen" breaks stuff. I can get it to work fine if i change my monitor output to 1920x1080. but thats not very great.

i3wm is obviously not the ideal gaming wm, but aside from the 1080p hardcoding, this is actually pretty smooth working. Very excited about this.

**Comment by AsherGlick** [comment]
Closing with the merge of #39.
