### ISSUE TITLE
Lutris issue when extracting environment variables

### ISSUE THREAD

**Issue by AudioEmu** [AsherGlick/Burrito#345]
I'm following the install instructions on the burrito homepage, but at step 2 where you create the launcher script I get the following error:

`hunter@hunter-mint:~$ flatpak run net.lutris.Lutris guild-wars-2  --output-script `pwd`/run_burrito_link.sh
Gtk-Message: 19:59:57.591: Failed to load module "xapp-gtk3-module"
2024-09-03 19:59:57,674: Command 'fluidsynth' not found on your system
2024-09-03 19:59:58,107: Starting Lutris 0.5.17
MESA: error: Use of VkSurfacePresentModeCompatibilityEXT without a VkSurfacePresentModeEXT set. This is an application bug.
2024-09-03 19:59:58,153: AMD Radeon RX 6600 (1002:73ff 1462:5022 amdgpu) Driver 24.1.3
2024-09-03 19:59:58,260: Shutting down Lutris
`

Based on what I've looked up, it may be because I use flatpak Lutris, or it may be because of my AMD card, or it may be because of the fluidsynth issue, but I can't find any info on that. Or may be a completely unrelated other issue lol

Any idea on how to fix this?

**Comment by AsherGlick** [comment]
The best way to ignore this is to use the `d3d11.dll` burrito link file instead of the `burrito_link.exe` executable. The dll is automatically loaded with all the correct configuration and environment because it is loaded by the gw2 process directly, instead of the `.exe` needing to be placed in the correct wine prefix.

**Comment by AudioEmu** [comment]
I was hoping to avoid using that dll because it crashes GW2 at the character select screen. I knew it was a sort of unsupported feature so I figured I'd wait for it to be further developed before trying it again.

I'm gonna try the arcdps extension method and see if that works.

**Comment by AsherGlick** [comment]
Can you send the crash log? I have not had any reports of it crashing on any systems yet. We do resurface all of the d3d11 functions that are needed afaik, but there could always be something missing.

**Comment by AudioEmu** [comment]
At character select, the crash reporter appears. I can move it around and continue to play with it visible, but as soon as I close it the game crashes.

Notably, the version found in the main burrito download in /burrito_link works when loaded via arcdps. The one I tried running by itself is the one downloaded individually straight from Burrito's homepage. I'm gonna try and run the included one alone and see if maybe they're different versions or something.

[ArenaNet.log](https://github.com/user-attachments/files/16859615/ArenaNet.log)

**Comment by AudioEmu** [comment]
Update: The bundled version works as a standalone too, the issue appears to be the version linked on the homepage under Burrito Link DLL Preview

**Comment by AsherGlick** [comment]
Thanks for the info and the debugging. I really need to do a new pass of the homepage. Especially if it is now giving outdated info. I will do that once we get xml_converter merged as I'll need to do one then anyways.
