### ISSUE TITLE
Question About Marker Conversion On The User Side

### ISSUE THREAD

**Issue by jimmon89** [AsherGlick/Burrito#50]
Is there currently a way to convert marker data from the TacO format to Burrito's JSON format on our side as the user?
i ask because i'd like to have markers based on the latest [GW2 TacO ReActif Pack](https://www.heinze.fr/taco/?lang=en)
if it's not currently feasible user side, it's okay and completely understandable.
i was just curious if there was anything i could do at the moment

**Comment by AsherGlick** [comment]
Right now there is [scripts/taco_to_burrito.py](https://github.com/AsherGlick/Burrito/blob/60927eff6a91d62175fe0f8a4c823654f384065b/scripts/taco_to_burrito.py) which handles converting between the file formats. There has also been some work to allow burrito to ingest the xml files directly via the [taco_parser](https://github.com/AsherGlick/Burrito/tree/master/taco_parser).

**Comment by jimmon89** [comment]
> Right now there is [scripts/taco_to_burrito.py](https://github.com/AsherGlick/Burrito/blob/60927eff6a91d62175fe0f8a4c823654f384065b/scripts/taco_to_burrito.py) which handles converting between the file formats. There has also been some work to allow burrito to ingest the xml files directly via the [taco_parser](https://github.com/AsherGlick/Burrito/tree/master/taco_parser).

you sir and/or madame are an absolute legend!
that's exactly what i was looking for
TYVM, cheers!
