### ISSUE TITLE
Minimap offset seems wrong

### ISSUE THREAD

**Issue by aeris** [AsherGlick/Burrito#51]
Hello and thanks for this Linux friendly TaCo <3

Markers on main interface and fullscreen map are good, but seems offset minimap wrong, real path (red) is under the displayed path (yellow).[](url)
![image](https://user-images.githubusercontent.com/51246/147878825-e96b59c7-434e-447a-bc6a-26141942639c.png)

**Comment by AsherGlick** [comment]
Can you share a screenshot of your entire gw2 window, additionally share what window manager you are using? The 2D path seems to be spilling out of the top of the minimap too which makes me think that the problem could just be that the overlay is misaligned to the window (#8).

**Comment by aeris** [comment]
Here is the full screen screenshot.
![image](https://user-images.githubusercontent.com/51246/147888117-9e1e9fd4-c068-41d1-8a07-49ce504411c2.png)
Seems overlay is a little too small in height

Perhaps double screen trouble? Seems it's my secondary screen height (1680x1050) and not my primary one (1920x1200).

Window manager : KDE / plasma / X11

**Comment by aeris** [comment]
Seems not the case, with a screen on the border between both monitors, red border for burrito seems to match nothing. Higher than my secondary screen but smaller than my primary :thinking:
![2022-01-02_21-11](https://user-images.githubusercontent.com/51246/147888322-2ecc89dc-c5f8-49b3-806f-58292321106d.png)

**Comment by AsherGlick** [comment]
I see the issue causing you problems. You have a 1920x1200 screen and in the version of burrito you are using it is locked to 1920x1080. It is the bottom of the screen not extending all the way down to the game. Good news is that there are some patches in git that will probably fix this (#29, #39), and worst case there is an option now to allow for a fixed size to be specified (#49) but I have not yet had time to release the new bundles to the live site.

**Comment by aeris** [comment]
:+1: Will try this :blush:

**Comment by aeris** [comment]
Seems that, built from master with fixed size, minimap ok.
But master not really usable now, always starting wrong screen and tedious to move after launch :rofl: 
I will patch release source to have a more usable binary.
Thanks for the tips.

**Comment by AsherGlick** [comment]
That is great that the size issue is taken care of. If you think this issue now is similar enough to #8 then you can close this and we can continue tracking it there. But if there is still something specific you are dealing with go head and add more info here describing the issue.

**Comment by aeris** [comment]
It's seem the same kind of trouble, so I close this :)
