### ISSUE TITLE
xml parser with prefiltering by a rapid xml wrapper

### ISSUE THREAD

**Issue by coderedart** [AsherGlick/Burrito#52]
full details https://gitlab.com/coderedart/jokolay/-/issues/21#note_805580495
I am trying to finalize the details how jokolay handles marker packs. to make things as simple as possible so that i can implement merging marker packs or splitting them, able to edit and send only the "json patches" (apparently, there's json-diff rfc :D ) etc.. but ofcourse, a lot of it was work to make sure that xmlpack could be converted to and from jsonpack without any loss of details from the user perspective. to achieve that, i needed to smh make sure that i'm reading a pack, just like taco does (including the "quirks").
after some messy work, i was able to successfully use rust x cpp bindings to deserialize xml, deduplicate nodes and serialize again with rapid xml, which would allow us to skip A LOT of errors with syntax/formatting when we use rust xml crates. 
at the moment, we still need to deal with attribute names which are misspelled like misNize instead of minSize, or weird values of attributes like alpha="3.0" etc. there's a bunch of work to do like writing tests, handling exceptions properly etc.. 

I have been trying to make it simpler so that i can be used by other crates too. just wanted to know if Burrito interested in this. either by extending the crate already used in Burrito  by using bindings or just simply using jokolay's crate directly. as far as i know, the only function that Burrito needs is xml_to_json_pack where it supplies the .taco archive to the crate and it returns back the .zip with all xml files merged into one json.

if you choose to extend the existing crate, i will send in a pr after i make sure that it is polished enough. unless someone really wants to extend it themselves because ffi is fun :)
if you choose to use jokolay's marker format crate, I would appreciate it if you give me any criticisms after reading the offtopic stuff at the bottom before i finalize all the details of a json marker pack or tell me if you have any particular ideas. at first i was really anxious to ask this because well.. its hard to ask others for their time (especially when i am noob ) , but between the timelines where i try and where i don't try at all, i will want to live in the timeline where i tried.
### OFFTOPIC
you can ignore this following as its not directly related to Burrito itself. this is just me asking for advice :) 
as of right now, tekkit's pack which has ever 35k markers (stats from https://mp-repo.blishhud.com/ ) and 3-5k categories can be put into a json of around 6-8 MB in size. 
Blish tries to split a xml marker pack into files named by the map id (eg: queensdale is 15.xml). so that i can only load the markers from that file when a player loads into a pack.
 I had no intention of doing so because jokolay uses super high quality crates and fortunately, keeps the memory usage down reasonably, and by having full marker pack in ram it simplifies stuff like editing markers where i can be SURE that when i create a marker with an id, it is unique across the pack. 
but other overlays might run into issues with such large packs, and it is true that when not editing a pack, just loading only the markers from the current map is better.  jokolay can still load all markers from all map files even if the marker pack is split into multiple files, so this decision is purely based on what other overlays would desire. 
Burrito, OTOH, splits marker pack into files based on category, which is not feasible when we are running into thousands of categories in a single pack.the jsonpack also only involves the markers/trails, the trail binaries themselves are stored as a mesh in their model space with first node set to origin, so they can be used by multiple trail tags by just specifying a position, and we can just transform/offset the mesh. these binaries are version 3. imagine if you made a trail that is a circle of radius 5 meters, and then you can just use it EVERYWHERE instead of re-recording trails OR even worse, duplicating them for every Trail Tag. this is partially motivated in hopes we can all eventually store these marker packs as gltf scenes, which i'm sure Burrito (which uses godot) as well as Electaco (which uses three.js) would really appreciate as both of them natively support gltf (and all the benefits like optimisation eg: compressed meshes, textures like ktx2/binomial, all the tooling whether offline or online etc..). well, it is still far, but a good dream. 
and this might also eventually lead to this area tag https://github.com/AsherGlick/Burrito/issues/10 that has an open issue. version 4 trails will automatically connect the first and last nodes of a trail to create a polygon which can serve as area. can be used everywhere with the position offset specified in Trail tag of xml/json. ofcourse, all of these would need to be exported back to version 2 trails which taco uses when exporting it to an xml pack.

**Comment by AsherGlick** [comment]
Integrating a parser that uses rapidxml seems like a good idea and was something which has been bouncing around in the back of my head for a while. The current JSON implementation is not a long term solution, and whatever the next phase was going to be I wanted to make sure that users could enable/disable specific markers or categories easily. If you already have C++ code that is able to do the parsing and are willing to share it, it would be welcome. However if it is C++ code then it might be best if it is just a C++ module instead of a Rust module that calls C++ code.

The reason burrito separates on category instead of map was purely due to the lack of being able to enable/disable specific marker categories. Eventually moving to a per-map system similar to the one you described for how blish-hud works would be ideal. Generating overlapping UUIDs is not a real concern for me, and if some other unique id was necessary simple prepending the map id in front would guarantee that only the other ids within a map file would need to be checked.

I am not fully sure I understand the point about saving paths as gltf scenes and their ability to be reused elsewhere. Maybe I am not seeing the same use case as you are for this functionality.

**Comment by coderedart** [comment]
the use for rapidxml wrapper is to filter out xml errors (syntax) by deserializing with rapidxml , doing some quick stuff like deduplicating nodes and serializing with it again into a proper xml (ignoring the weird asterisks for now ). with rust, you can rely on its safety when people contribute. nobody causing segmentation faults / random crashes is a huge boon.  but its your choice ofcourse. 

the c++ code which we would like to bind to. 
https://gitlab.com/coderedart/jokolay/-/blob/marker_manager/jmf/rapid/rapid.cpp

the rust code that generates the c++ binding by matching the rust signatures against the c++ header *at compile time*. barely 10 lines. so, if it compiles, it works. they even provide convenience classes like rust::String (can be used to get a std::string) or Vector or UniquePtr which will match across ffi boundaries. so, no errors of struct layouts or nullptrs or other dangerous stuff. you can still cause segfaults in cpp side of code. but as long as you review any cpp contributions, i think there should be no issues. again,
https://gitlab.com/coderedart/jokolay/-/blob/marker_manager/jmf/src/xmlpack/rapid.rs

the rust script which compiles the rapidxml. rapidxml is abandoned since 2013, so there's LOTS of warnings in print header about lack of forward declarations, so i need the -fpermissive flag for now. its barely 10 lines. maybe couple more to make it work on msvc.
https://gitlab.com/coderedart/jokolay/-/blob/marker_manager/jmf/build.rs

its just these three files (ofcourse, including rapidxml headers in include folder) and once i understood how it worked, it felt really simple. its a static library, so no cpp dll/so files.  I will take a little more time to write some basic tests and check that it works on windows first.

### Offtopic


about the ids, i use simple u16 instead of UUID. I only cared about uniqueness within the pack and no pack has 65k+ markers. using map (u16) + marker (u16) will also make them unique within a pack and packid + mapid + markerid will make it unique across packs. 


#### gltf dream : just a potential future consideration
Blish already supports rotation attribute to enabled 2d markers to be "3d" by not being billboards and instead face a certain direction. 
Quitar of the hero marker pack is already bringing 3d markers (well 3d objects literally at this point) into his marker pack with blish. 
https://cdn.discordapp.com/attachments/575704832606994439/929791078763216936/Blish_Sign.webm
at which point will we realize that we are just creating 3d scenes and use gltf instead of a custom marker format xD then there's https://youtu.be/0zCxpMS7ul0?t=7059 ktx2 textures which are termed as jpeg but for textures, useful as more people start creating marker packs, which they will do as blish already is working on a marker editor gui . people WILL want 4k anime cat girls marker pack sooner or later :D again, just a consideration. 

### Version 3 Trails
consider trail meshes just as what they already are, but their position offset to origin in the binary. recently, tekkit released fractal marker packs. and he posted this picture. 
![image](https://user-images.githubusercontent.com/24411704/148837754-52002b2e-42b7-4e68-8814-94f6b22651e3.png)

as you can see, all those red aoe circles are marked with trails. aoe circles are not uncommon (eg: guild races), and instead of having a version two trail for each of those circles, we can have a single version 3 trail mesh. the trail mesh will be in model space with the first node being [0.0 , 0.0, 0.0]. now trail tags can have a position attribute like markers, then we can just offset the mesh to that position with a simple model matrix multiplication ( no duplication of meshes in gpu either). 

##### Common Format
I spent like 70%+ of my jokolay development time on marker formats xD I cringe everytime i think about it. but its been a lot of fun considering performance, flexibility and other tradeoffs with every design. https://gitlab.com/coderedart/jokolay/-/issues/19 will have most of the changes documented about final details of marker format as i will start working on alpha release of jokolay this month.
 at the moment, burrito only cares about three things from the looks of https://github.com/AsherGlick/Burrito/blob/master/taco_parser/src/xml_parser.rs
```rust
struct Path {
    texture: String, // texture is now associated with the mesh directly rather than Trail Tag deciding that.
    points: Vec<[f32; 3]>,
}
struct Icon {
    position: [f32; 3],
    texture: String, // oof, so many String allocations :( memory fragmentation + cache misses due to heap indirection
}
```
position of marker, points/nodes of trail mesh, texture.  the real complexity in marker packs lies in recursive marker categories and inheritance, both of which i sorta tried to remove in jokolay by disabling inheritance as well as separating categories from the menu itself.  if you like those changes in the linked issue, its great. otherwise, we can  just continue separately with our own marker formats,  while trying to coordinate in regards to X11 issues as usual. i'm not asking Burrito to use jokolay's marker format btw, just saying that by expressing your priorities now before i commit to the design, we can keep the hope of a common format alive IF Burrito/Jokolay wanted to use the same format in the future.

**Comment by AsherGlick** [comment]
I really like rust, but it needs to be remembered that Rust safety is purely around memory safety, not crash safety such as segfaults and other assorted panics. EG: things like `panic!` `todo!` and `.unwrap()` exist which will just crash the program if called (likewise some things like the subscript operator [] can panic because it returns a value instead of a result). Additionally if you are calling into c++ code then said safety guarantees disappear.

My rationale for ignoring rust in this XML parser module is that we don't get any of the safety features from rust because the parsing is being done by C++ and then the result is being handed off to gdscript, so the added complexity has less benefit then it does with jokolay which is already in rust. In general something with more complexity is harder to maintain, so I want to keep as much complexity away as possible.

Honestly I think that spending so much time on optimizing marker files is a great thing if it is something you enjoy doing, but be sure that the optimizations don't come at the cost of unnecessary complexity. There is a lot here that I don't have the time to address right now but I think that is it a good concept to discuss to try and find an optimal format. I have had some ideas of my own and I will need to finish fleshing them out then compare them with yours in order to come up with any kind of meaningful critique from me.

**Comment by coderedart** [comment]
there's clippy lints for all of those crash causing unwraps etc.. you mentioned which will catch them at compile time (CI). but yeah, Burrito  might have better time directly integrating with c++ with gdnative. 

there is https://github.com/timniederhausen/rapidxml which seems more maintained with fixes to compiler errors/warnings that i mentioned previously. 

in support of rust though, compared to just adding the wrapper to existing rust code which will be a few minutes of work, a pure c++ solution will be much more manual work.
