### ISSUE TITLE
Converting Teh's Trails

### ISSUE THREAD

**Issue by anilozlu** [AsherGlick/Burrito#54]
I see that taco_to_burrito.py should be able to convert Teh's Trails successfully with some adjustments to the XML file. Can I get the adjusted XML file or a list of adjustments that I need to make to make it work? Currently, I am unable to convert it.

**Comment by anilozlu** [comment]
Thanks for the reply, I couldn't figure out that I needed spaces after attributes, now it can convert and it works! When I delete other colors, I get black lines instead of trails though, not sure why. I can make do with rainbow trails for now I think.

Looking at the teaser for this pack (https://streamable.com/nrdjxe), it seems that I should get a text on my screen when I enter a heart location but I'm not getting that. Is this because burrito doesn't support this feature yet?

**Comment by TarEnethil** [comment]
> Looking at the teaser for this pack (https://streamable.com/nrdjxe), it seems that I should get a text on my screen when I enter a heart location but I'm not getting that. Is this because burrito doesn't support this feature yet?
Yes, I don't think Burrito supports the "info" attribute yet. As I have never used any overlays before Burrito, I don't know what Teh's Trails is supposed to look like / what the full range of information it contains is. But I can say that I have used the converted version for 3 map completions with reasonable success (around 12-13 hours).

**Comment by anilozlu** [comment]
I hope it gets implemented soon, it would be really useful for raid timers as well. Thanks for your help, I am closing this issue now.

**Comment by Zeluok** [comment]
I know this is closed, but

```
:%s!/[&B!\&amp;B!g
```
and
```
tidy -o teh.xml --input-xml yes --output-xml yes --quote-ampersand yes --quote-marks yes TehsTrails.xml
```
before
```
python taco_to_burrito.py [TEH_DIR] json_teh
```

May help someone in the future
