### ISSUE TITLE
Burrito markers failed to load / which marker should I download?

### ISSUE THREAD

**Issue by Mistreaper** [AsherGlick/Burrito#60]
I saw this video: https://www.reddit.com/r/Guildwars2/comments/ou7ebj/tekkits_workshop_markers_running_on_linux/, and I'm curious how you got that running.

The Burrito runs well (with the exception of windowed fullscreen, of course), but the markers failed to load. Loading the "converted_markers.zip" file gave this output:

```
Unicode error: no space left
Unicode error: invalid skip
ERROR: parse: Error parsing JSON at line 0: Expected 'true','false' or 'null', got 'PK'.
   At: core/bind/core_bind.cpp:3292.
```
The markers are downloaded from this [site](https://burrito.orthogonalprojects.com), by clicking the "Download Markers" button.

The video on Reddit, it seems to be working very well. Did you use the marker pack from the official website or from [here](https://www.tekkitsworkshop.net/index.php/download)? Which version of Burrito was that?

FYI, the "Burrito Link" works perfectly fine, it shows the output of the character name and more information.

**Comment by AsherGlick** [comment]
You must extract the zip file and load the json objects within.

**Comment by Mistreaper** [comment]
> You must extract the zip file and load the json objects within.

Thanks, it works perfectly. I like this project.
