### ISSUE TITLE
[XML Markers] Implement generated `init_xml_attribute()`

### ISSUE THREAD

**Issue by AsherGlick** [AsherGlick/Burrito#67]
The new generated classes written in #65 need a way to parse XML values into the member variables. This will be done by implementing the now virtual function:

```c++
bool init_xml_attribute(rapidxml::xml_attribute<>* attribute, vector<XMLError*> *errors);
```

This function will have static code inside of it such that it is able to translate from any of the stringy attribute names, found in the `xml_fields` value of any of the [xml docs](https://github.com/AsherGlick/Burrito/tree/xml_converter/xml_converter/doc)'s frontmatter, to specific logic for setting the associated class variable.

One option may be to use [gperf](https://linux.die.net/man/1/gperf) to generate a perfect hash lookup table at compile time.

**Comment by klingbolt** [comment]
I will take this assignment
